//! # Module: pkg/lockfile.rs — Package lockfile management
//!
//! Manages `~/.config/mae/packages.lock` — a TOML file tracking pinned
//! package versions. Users commit this to their dotfiles VCS for
//! reproducible package state across machines.

use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use std::io;
use std::path::{Path, PathBuf};

/// A single package pin in the lockfile.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PackagePin {
    /// Source spec (e.g. "github:user/repo").
    pub source: String,
    /// Exact git SHA.
    pub sha: String,
    /// SHA-256 of module.toml content (integrity check).
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub integrity: String,
    /// ISO 8601 timestamp when this pin was created/updated.
    pub locked_at: String,
}

/// The lockfile — tracks all pinned packages.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Lockfile {
    /// Package name → pin data.
    #[serde(default)]
    pub packages: BTreeMap<String, PackagePin>,
}

impl Lockfile {
    /// Load lockfile from disk.
    ///
    /// A **missing** file is `Ok(empty)` — that is the legitimate first-run
    /// state. A file that exists but does not parse is `Err`, NOT an empty
    /// lockfile: this file is the user's committed record of every pinned
    /// package, so silently degrading a corrupt or half-written one to "no
    /// packages" loses data the moment anything saves over it.
    pub fn load_checked(path: &Path) -> Result<Self, String> {
        let content = match std::fs::read_to_string(path) {
            Ok(c) => c,
            Err(e) if e.kind() == io::ErrorKind::NotFound => return Ok(Self::default()),
            Err(e) => return Err(format!("Failed to read {}: {e}", path.display())),
        };
        toml::from_str(&content).map_err(|e| {
            format!(
                "{} is not valid lockfile TOML: {e}. Refusing to treat it as empty — \
                 fix or delete the file (it is meant to be committed to version control).",
                path.display()
            )
        })
    }

    /// Load lockfile from disk, returning empty on any failure.
    ///
    /// @ai-caution: [data-loss] Read-only callers ONLY. This collapses a
    /// corrupt lockfile to an empty one, so anything that loads through here
    /// and later saves will overwrite the user's real pins with nothing (audit
    /// #607.7). Mutating flows must use `load_checked`/`update`, which refuse
    /// to write over a lockfile they could not read.
    pub fn load(path: &Path) -> Self {
        Self::load_checked(path).unwrap_or_else(|e| {
            tracing::warn!("{e}");
            Self::default()
        })
    }

    /// Write lockfile to disk.
    pub fn save(&self, path: &Path) -> Result<(), String> {
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)
                .map_err(|e| format!("Failed to create lockfile directory: {}", e))?;
        }
        let content = toml::to_string_pretty(self)
            .map_err(|e| format!("Failed to serialize lockfile: {}", e))?;
        let header = "# MAE packages.lock — auto-generated by `mae sync`\n\
                      # Commit this file to version control for reproducible package state.\n\n";
        std::fs::write(path, format!("{}{}", header, content))
            .map_err(|e| format!("Failed to write lockfile: {}", e))
    }

    /// Pin a package.
    pub fn pin(&mut self, name: &str, source: &str, sha: &str, integrity: &str) {
        let now = {
            let secs = std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap_or_default()
                .as_secs();
            format!("{}", secs)
        };
        self.packages.insert(
            name.to_string(),
            PackagePin {
                source: source.to_string(),
                sha: sha.to_string(),
                integrity: integrity.to_string(),
                locked_at: now,
            },
        );
    }

    /// Remove a package pin.
    pub fn unpin(&mut self, name: &str) -> bool {
        self.packages.remove(name).is_some()
    }

    /// Get a package pin.
    pub fn get(&self, name: &str) -> Option<&PackagePin> {
        self.packages.get(name)
    }

    /// Reload-fresh -> mutate -> save, under a cross-process advisory lock.
    /// Same rationale as `KbRegistry::update`/`ProjectList::update`: `mae
    /// sync`/`upgrade`/`purge` invocations in different terminals shouldn't
    /// clobber each other's pins on save.
    ///
    /// Deliberately NOT used to wrap the whole `sync`/`upgrade`/`purge`
    /// command — those do per-package git network I/O in a loop that can
    /// take minutes and don't read back from the loaded lockfile to make any
    /// decisions (it's purely an accumulator for this run's own pins). Only
    /// the final apply-and-persist step needs the lock; callers should apply
    /// just the pins/unpins this run actually decided on inside `mutate`.
    ///
    /// Fails **closed** on an unreadable existing lockfile (audit #607.7): the
    /// load and the save are both inside the advisory lock, so if the on-disk
    /// file exists but does not parse, this reports the error and writes
    /// nothing rather than replacing the user's pins with an empty file.
    pub fn update<R>(
        path: &Path,
        mutate: impl FnOnce(&mut Self) -> R,
    ) -> (Self, R, io::Result<()>) {
        // Set inside the lock by `load`, read inside the lock by `save`.
        let corrupt: std::cell::RefCell<Option<String>> = std::cell::RefCell::new(None);
        mae_mcp::file_lock::with_locked_update(
            path,
            || match Self::load_checked(path) {
                Ok(lf) => lf,
                Err(e) => {
                    *corrupt.borrow_mut() = Some(e);
                    Self::default()
                }
            },
            mutate,
            |lf| match corrupt.borrow().as_deref() {
                Some(e) => Err(io::Error::other(format!(
                    "{e} (no changes were written — the existing lockfile was left intact)"
                ))),
                None => lf.save(path).map_err(io::Error::other),
            },
        )
    }

    /// Default lockfile path.
    pub fn default_path() -> PathBuf {
        crate::bootstrap::dirs_candidate("mae/packages.lock")
            .unwrap_or_else(|| PathBuf::from("packages.lock"))
    }
}

/// Compute the SHA-256 of a byte slice as lowercase hex.
///
/// The single implementation for the whole binary: package `integrity` pins
/// here, and release-archive checksum verification in `crate::upgrade`.
///
/// @ai-caution: [security] In-process via `sha2`, never a subprocess. This
/// previously shelled out to `sha256sum` and, when that was absent, fell back
/// to a 64-bit non-cryptographic multiply-add "hash" (audit #607.2). That
/// fallback fired on **every macOS machine** — macOS ships `shasum -a 256`, not
/// `sha256sum` — so a value being compared for integrity was silently a
/// trivially-forgeable 16-hex-digit digest on one of MAE's two primary
/// platforms, and produced a different string than Linux for identical bytes
/// (principle #13). Do not reintroduce a subprocess or a fallback here.
pub fn sha256_hex(data: &[u8]) -> String {
    use sha2::{Digest, Sha256};
    let mut hasher = Sha256::new();
    hasher.update(data);
    hasher
        .finalize()
        .iter()
        .map(|b| format!("{b:02x}"))
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::NamedTempFile;

    #[test]
    fn lockfile_roundtrip() {
        let mut lf = Lockfile::default();
        lf.pin("org-roam", "github:user/mae-org-roam", "abc123", "def456");

        let tmp = NamedTempFile::new().unwrap();
        lf.save(tmp.path()).unwrap();
        let loaded = Lockfile::load(tmp.path());

        assert_eq!(loaded.packages.len(), 1);
        let pin = loaded.get("org-roam").unwrap();
        assert_eq!(pin.source, "github:user/mae-org-roam");
        assert_eq!(pin.sha, "abc123");
        assert_eq!(pin.integrity, "def456");
    }

    #[test]
    fn lockfile_pin_and_get() {
        let mut lf = Lockfile::default();
        assert!(lf.get("foo").is_none());
        lf.pin("foo", "github:u/r", "sha1", "");
        assert!(lf.get("foo").is_some());
    }

    #[test]
    fn lockfile_unpin() {
        let mut lf = Lockfile::default();
        lf.pin("foo", "github:u/r", "sha1", "");
        assert!(lf.unpin("foo"));
        assert!(!lf.unpin("foo"));
    }

    #[test]
    fn empty_lockfile_loads() {
        let tmp = NamedTempFile::new().unwrap();
        std::fs::write(tmp.path(), "").unwrap();
        let lf = Lockfile::load(tmp.path());
        assert!(lf.packages.is_empty());
    }

    #[test]
    fn integrity_hash_deterministic() {
        let data = b"hello world";
        let h1 = sha256_hex(data);
        let h2 = sha256_hex(data);
        assert_eq!(h1, h2);
        assert!(!h1.is_empty());
    }

    /// Audit #607.2 — `sha256_hex` shelled out to `sha256sum` and, where that
    /// binary is absent (every macOS box), silently returned a 16-hex-digit
    /// non-cryptographic hash instead. Pin the published NIST vectors so the
    /// function is checked against SHA-256 itself, not against its own past
    /// output: a determinism-only test passed happily on the broken fallback.
    #[test]
    fn sha256_matches_published_vectors_on_every_platform() {
        assert_eq!(
            sha256_hex(b""),
            "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
        );
        assert_eq!(
            sha256_hex(b"abc"),
            "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad"
        );
        assert_eq!(
            sha256_hex(b"abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq"),
            "248d6a61d20638b8e5c026930c3e6039a33ce45964ff2167f6ecedd419db06c1"
        );
        // 64 hex chars, always — the old fallback produced 16.
        assert_eq!(sha256_hex(b"anything").len(), 64);
        // Avalanche: a one-bit difference must not collide (the old fallback's
        // multiply-add over 64 bits made near-neighbours cheap to construct).
        assert_ne!(sha256_hex(b"integrity"), sha256_hex(b"integritz"));
    }

    /// Audit #607.7 — the data-loss test. `packages.lock` is documented as a
    /// file to COMMIT to version control; a truncated or hand-mangled one used
    /// to parse-fail silently into an empty `Lockfile`, and the very next
    /// `update()` persisted that emptiness over every real pin the user had.
    #[test]
    fn a_corrupt_lockfile_is_never_silently_emptied_or_overwritten() {
        // Several genuinely different corruptions, not one hand-picked string:
        // a truncated write, invalid TOML, and a well-formed TOML file with the
        // wrong shape.
        let corruptions = [
            "# MAE packages.lock\n[packages.org-roam]\nsource = \"github:u/r\"\nsha = \"ab",
            "this is not toml at all {{{",
            "[packages]\norg-roam = \"not-a-table\"\n",
        ];

        for original in corruptions {
            let tmp = NamedTempFile::new().unwrap();
            std::fs::write(tmp.path(), original).unwrap();

            // 1. The checked load reports the failure instead of inventing an
            //    empty lockfile.
            let err = Lockfile::load_checked(tmp.path())
                .expect_err("a corrupt lockfile must not parse as empty");
            assert!(
                err.contains("not valid lockfile TOML"),
                "unhelpful error: {err}"
            );

            // 2. `update` — the mutating path every `mae sync`/`upgrade`/`purge`
            //    goes through — must refuse to write and leave the bytes alone.
            let (_lf, (), saved) = Lockfile::update(tmp.path(), |lf| {
                lf.pin("newpkg", "github:u/r", "sha", "");
            });
            assert!(saved.is_err(), "update must fail closed on a corrupt file");

            let after = std::fs::read_to_string(tmp.path()).unwrap();
            assert_eq!(
                after, original,
                "the on-disk lockfile must be byte-identical after a refused update"
            );
        }
    }

    /// The complementary case — a *missing* lockfile is the legitimate
    /// first-run state and must still load empty and save normally, or the
    /// guard above would have broken `mae sync` on a fresh machine.
    #[test]
    fn a_missing_lockfile_is_not_treated_as_corrupt() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("packages.lock");
        assert!(Lockfile::load_checked(&path).unwrap().packages.is_empty());

        let (_lf, (), saved) = Lockfile::update(&path, |lf| {
            lf.pin("newpkg", "github:u/r", "sha", "");
        });
        assert!(saved.is_ok(), "first-run save must succeed: {saved:?}");
        assert!(Lockfile::load_checked(&path)
            .unwrap()
            .get("newpkg")
            .is_some());
    }
}
