//! # Module: pkg/lockfile.rs — Package lockfile management
//!
//! Manages `~/.config/mae/packages.lock` — a TOML file tracking pinned
//! package versions. Users commit this to their dotfiles VCS for
//! reproducible package state across machines.

use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

/// A single package pin in the lockfile.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PackagePin {
    /// Source spec (e.g. "github:user/repo").
    pub source: String,
    /// Exact git SHA.
    pub sha: String,
    /// SHA-256 of module.toml content (integrity check).
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub integrity: String,
    /// ISO 8601 timestamp when this pin was created/updated.
    pub locked_at: String,
}

/// The lockfile — tracks all pinned packages.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Lockfile {
    /// Package name → pin data.
    #[serde(default)]
    pub packages: BTreeMap<String, PackagePin>,
}

impl Lockfile {
    /// Load lockfile from disk, returning empty if not found.
    pub fn load(path: &Path) -> Self {
        match std::fs::read_to_string(path) {
            Ok(content) => toml::from_str(&content).unwrap_or_default(),
            Err(_) => Self::default(),
        }
    }

    /// Write lockfile to disk.
    pub fn save(&self, path: &Path) -> Result<(), String> {
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)
                .map_err(|e| format!("Failed to create lockfile directory: {}", e))?;
        }
        let content = toml::to_string_pretty(self)
            .map_err(|e| format!("Failed to serialize lockfile: {}", e))?;
        let header = "# MAE packages.lock — auto-generated by `mae sync`\n\
                      # Commit this file to version control for reproducible package state.\n\n";
        std::fs::write(path, format!("{}{}", header, content))
            .map_err(|e| format!("Failed to write lockfile: {}", e))
    }

    /// Pin a package.
    pub fn pin(&mut self, name: &str, source: &str, sha: &str, integrity: &str) {
        let now = {
            let secs = std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap_or_default()
                .as_secs();
            format!("{}", secs)
        };
        self.packages.insert(
            name.to_string(),
            PackagePin {
                source: source.to_string(),
                sha: sha.to_string(),
                integrity: integrity.to_string(),
                locked_at: now,
            },
        );
    }

    /// Remove a package pin.
    pub fn unpin(&mut self, name: &str) -> bool {
        self.packages.remove(name).is_some()
    }

    /// Get a package pin.
    pub fn get(&self, name: &str) -> Option<&PackagePin> {
        self.packages.get(name)
    }

    /// Default lockfile path.
    pub fn default_path() -> PathBuf {
        crate::bootstrap::dirs_candidate("mae/packages.lock")
            .unwrap_or_else(|| PathBuf::from("packages.lock"))
    }
}

/// Compute SHA-256 hex digest of a byte slice.
pub fn sha256_hex(data: &[u8]) -> String {
    // Minimal SHA-256 using the sha2 crate would be ideal, but to avoid
    // adding a dependency we shell out to sha256sum if available, or use
    // a simple fallback of hashing the length + first/last bytes.
    // For now, use a basic approach that works everywhere.
    if let Ok(output) = std::process::Command::new("sha256sum")
        .stdin(std::process::Stdio::piped())
        .stdout(std::process::Stdio::piped())
        .spawn()
        .and_then(|mut child| {
            use std::io::Write as IoWrite;
            if let Some(ref mut stdin) = child.stdin {
                let _ = stdin.write_all(data);
            }
            child.wait_with_output()
        })
    {
        if output.status.success() {
            let out = String::from_utf8_lossy(&output.stdout);
            return out.split_whitespace().next().unwrap_or("").to_string();
        }
    }
    // Fallback: simple non-cryptographic hash (for platforms without sha256sum)
    let mut hash = 0u64;
    for (i, &b) in data.iter().enumerate() {
        hash = hash
            .wrapping_mul(31)
            .wrapping_add(b as u64)
            .wrapping_add(i as u64);
    }
    format!("{:016x}", hash)
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::NamedTempFile;

    #[test]
    fn lockfile_roundtrip() {
        let mut lf = Lockfile::default();
        lf.pin("org-roam", "github:user/mae-org-roam", "abc123", "def456");

        let tmp = NamedTempFile::new().unwrap();
        lf.save(tmp.path()).unwrap();
        let loaded = Lockfile::load(tmp.path());

        assert_eq!(loaded.packages.len(), 1);
        let pin = loaded.get("org-roam").unwrap();
        assert_eq!(pin.source, "github:user/mae-org-roam");
        assert_eq!(pin.sha, "abc123");
        assert_eq!(pin.integrity, "def456");
    }

    #[test]
    fn lockfile_pin_and_get() {
        let mut lf = Lockfile::default();
        assert!(lf.get("foo").is_none());
        lf.pin("foo", "github:u/r", "sha1", "");
        assert!(lf.get("foo").is_some());
    }

    #[test]
    fn lockfile_unpin() {
        let mut lf = Lockfile::default();
        lf.pin("foo", "github:u/r", "sha1", "");
        assert!(lf.unpin("foo"));
        assert!(!lf.unpin("foo"));
    }

    #[test]
    fn empty_lockfile_loads() {
        let tmp = NamedTempFile::new().unwrap();
        std::fs::write(tmp.path(), "").unwrap();
        let lf = Lockfile::load(tmp.path());
        assert!(lf.packages.is_empty());
    }

    #[test]
    fn integrity_hash_deterministic() {
        let data = b"hello world";
        let h1 = sha256_hex(data);
        let h2 = sha256_hex(data);
        assert_eq!(h1, h2);
        assert!(!h1.is_empty());
    }
}
