//! `kb_export_guidance` — ADR-050 D4 / Phase H: a fallback exporter that
//! writes MAE's guidance context (project files + the designated guidance
//! KB's index body, `crate::guidance::build_guidance_context`) to a plain
//! markdown file (`AGENTS.md` by default, or `.github/copilot-instructions.md`
//! if you point `path` at it) so an external editor's agent sees the FULL
//! content, not just the pointer sentence MAE's MCP `initialize.instructions`
//! sends ("Before acting, consult KB '...' for required practices.") — that
//! field is deliberately a lightweight pointer, not the full guidance body
//! (kept small on principle; the agent is expected to follow up with
//! `kb_search`/`kb_get`). Whether a given host forwards `instructions` into
//! its model's context at all is a separate, per-host question this exporter
//! sidesteps entirely: it writes to a file the host reads unconditionally as
//! part of its own repo scan (`AGENTS.md`, `.github/copilot-instructions.md`).
//!
//! Additive-merge safety (the actual point of this file): re-running the
//! export must never clobber hand-written content sharing the target file.
//! A clearly delimited MAE-managed block is the only thing ever
//! written/replaced; anything outside it survives untouched, including on a
//! virgin file with none of MAE's markers at all (append below, never
//! overwrite).

use mae_core::Editor;

const BEGIN_MARKER: &str = "<!-- BEGIN MAE-MANAGED GUIDANCE (auto-generated by \
kb_export_guidance / :kb-export-guidance -- do not hand-edit this block, it will be \
overwritten on the next export) -->";
const END_MARKER: &str = "<!-- END MAE-MANAGED GUIDANCE -->";

/// Merge `guidance_body` into `existing` file content (`None` = file doesn't
/// exist yet), replacing only the MAE-managed block delimited by
/// `BEGIN_MARKER`/`END_MARKER`. Pure and independently testable — the actual
/// tool wrapper below just does the file I/O around this.
fn merge_guidance_block(existing: Option<&str>, guidance_body: &str) -> Result<String, String> {
    let block = format!("{BEGIN_MARKER}\n{guidance_body}\n{END_MARKER}\n");
    let Some(existing) = existing else {
        return Ok(block);
    };
    let begin_idx = existing.find(BEGIN_MARKER);
    let end_idx = existing.find(END_MARKER);
    match (begin_idx, end_idx) {
        (Some(b), Some(e)) if e > b => {
            let before = &existing[..b];
            let after = &existing[e + END_MARKER.len()..];
            // Our own block already ends in a newline -- drop one leading
            // newline from `after` if present so re-exporting doesn't grow a
            // blank line between the block and whatever follows it.
            let after = after.strip_prefix('\n').unwrap_or(after);
            Ok(format!("{before}{block}{after}"))
        }
        (None, None) => {
            // No existing MAE block at all -- append below, never touching
            // a single byte of what's already there. An empty existing file
            // is treated the same as no file: no leading blank line.
            let sep = if existing.is_empty() {
                ""
            } else if existing.ends_with('\n') {
                "\n"
            } else {
                "\n\n"
            };
            Ok(format!("{existing}{sep}{block}"))
        }
        _ => Err(format!(
            "found a MAE-managed guidance marker without its matching pair in the target \
             file -- refusing to write (would risk corrupting or duplicating content). Fix \
             the markers by hand (they must be exactly '{BEGIN_MARKER}' / '{END_MARKER}', \
             each on its own line) and retry."
        )),
    }
}

/// Export MAE's guidance context to a markdown file for external agents that
/// don't (or might not) consume MCP `initialize.instructions` themselves —
/// `AGENTS.md` by default; pass `path` to target `.github/copilot-instructions.md`
/// or anything else. Read-modify-write, additive-merge-safe (see module doc).
pub fn execute_kb_export_guidance(
    editor: &Editor,
    args: &serde_json::Value,
) -> Result<String, String> {
    let target = args
        .get("path")
        .and_then(|v| v.as_str())
        .unwrap_or("AGENTS.md");
    let root = editor
        .git_or_project_root()
        .ok_or("No project root open — kb_export_guidance needs a project to export into")?;
    let guidance_kb = editor
        .get_option("ai_guidance_kb")
        .map(|(v, _)| v)
        .unwrap_or_default();
    let data_dir = editor.mae_data_dir();
    let context = crate::guidance::build_guidance_context(&root, data_dir.as_deref(), &guidance_kb)
        .ok_or(
            "Nothing to export — set ai_guidance_kb and/or add a CLAUDE.md/README.md to the \
             project root first",
        )?;

    let out_path = root.join(target);
    let existing = std::fs::read_to_string(&out_path).ok();
    let merged = merge_guidance_block(existing.as_deref(), context.trim())?;

    if let Some(parent) = out_path.parent() {
        std::fs::create_dir_all(parent)
            .map_err(|e| format!("failed to create {}: {e}", parent.display()))?;
    }
    std::fs::write(&out_path, &merged)
        .map_err(|e| format!("failed to write {}: {e}", out_path.display()))?;

    Ok(format!(
        "Exported guidance to {} ({} bytes)",
        out_path.display(),
        merged.len()
    ))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn creates_fresh_content_when_no_file_exists() {
        let out = merge_guidance_block(None, "Always write tests first.").unwrap();
        assert!(out.starts_with(BEGIN_MARKER));
        assert!(out.contains("Always write tests first."));
        assert!(out.trim_end().ends_with(END_MARKER));
    }

    /// The DoD's explicit non-happy-path requirement: real, pre-existing
    /// hand-written content around the block must survive a fresh export
    /// byte-for-byte.
    #[test]
    fn appends_below_existing_hand_written_content_without_clobbering_it() {
        let hand_written = "# My Custom Agent Instructions\n\n\
             Please always use tabs, not spaces, in this repo.\n\
             Never touch the `vendor/` directory.\n";
        let out = merge_guidance_block(Some(hand_written), "Follow the style guide.").unwrap();
        assert!(
            out.starts_with(hand_written),
            "hand-written content must be preserved byte-for-byte at the start: {out}"
        );
        assert!(out.contains(BEGIN_MARKER));
        assert!(out.contains("Follow the style guide."));
    }

    #[test]
    fn re_export_replaces_only_the_managed_block_content_changes() {
        let first = merge_guidance_block(None, "version one guidance").unwrap();
        let with_user_content = format!(
            "# Team notes\nDo not remove this line.\n\n{first}\n## Trailing notes\nKeep this too.\n"
        );
        let second =
            merge_guidance_block(Some(&with_user_content), "version two guidance").unwrap();

        assert!(second.contains("Do not remove this line."));
        assert!(second.contains("Keep this too."));
        assert!(
            !second.contains("version one guidance"),
            "the stale managed block content must be gone: {second}"
        );
        assert!(second.contains("version two guidance"));
        // Exactly one instance of each marker -- no duplication.
        assert_eq!(second.matches(BEGIN_MARKER).count(), 1);
        assert_eq!(second.matches(END_MARKER).count(), 1);
    }

    #[test]
    fn refuses_to_write_when_markers_are_mismatched() {
        let corrupted = format!("some text\n{BEGIN_MARKER}\nno end marker here\n");
        let result = merge_guidance_block(Some(&corrupted), "new guidance");
        assert!(
            result.is_err(),
            "a lone BEGIN marker must be refused, not guessed at"
        );
    }

    #[test]
    fn appending_to_an_empty_string_does_not_produce_a_leading_blank_line() {
        let out = merge_guidance_block(Some(""), "guidance body").unwrap();
        assert!(out.starts_with(BEGIN_MARKER));
    }

    /// End-to-end through the real tool wrapper: a real `Editor` with a real
    /// project root, a real file write, default `path` ("AGENTS.md").
    #[test]
    fn integration_writes_agents_md_from_a_real_editor_and_project_root() {
        let tmp = tempfile::tempdir().unwrap();
        std::fs::write(tmp.path().join("CLAUDE.md"), "project rules for the test").unwrap();
        let mut editor = mae_core::Editor::new();
        editor.project = Some(mae_core::project::Project::from_root(
            tmp.path().to_path_buf(),
        ));

        let result = execute_kb_export_guidance(&editor, &serde_json::json!({}));
        assert!(result.is_ok(), "{result:?}");
        let out = std::fs::read_to_string(tmp.path().join("AGENTS.md")).unwrap();
        assert!(out.contains(BEGIN_MARKER));
        assert!(out.contains("project rules for the test"));
    }

    /// `path` targets an alternate file (e.g. the Copilot-specific
    /// convention), including creating the parent directory.
    #[test]
    fn integration_respects_a_custom_nested_path() {
        let tmp = tempfile::tempdir().unwrap();
        std::fs::write(tmp.path().join("README.md"), "readme guidance content").unwrap();
        let mut editor = mae_core::Editor::new();
        editor.project = Some(mae_core::project::Project::from_root(
            tmp.path().to_path_buf(),
        ));

        let result = execute_kb_export_guidance(
            &editor,
            &serde_json::json!({"path": ".github/copilot-instructions.md"}),
        );
        assert!(result.is_ok(), "{result:?}");
        let out =
            std::fs::read_to_string(tmp.path().join(".github/copilot-instructions.md")).unwrap();
        assert!(out.contains("readme guidance content"));
    }

    /// A second export against the same real file must preserve hand-written
    /// content that was added around the managed block in between runs —
    /// the additive-merge-safety guarantee, exercised through the real tool
    /// wrapper this time (not just the pure merge function above).
    #[test]
    fn integration_second_export_preserves_hand_written_additions() {
        let tmp = tempfile::tempdir().unwrap();
        std::fs::write(tmp.path().join("CLAUDE.md"), "v1 guidance").unwrap();
        let mut editor = mae_core::Editor::new();
        editor.project = Some(mae_core::project::Project::from_root(
            tmp.path().to_path_buf(),
        ));

        execute_kb_export_guidance(&editor, &serde_json::json!({})).unwrap();

        let agents_md = tmp.path().join("AGENTS.md");
        let mut content = std::fs::read_to_string(&agents_md).unwrap();
        content.push_str("\n## Human addendum\nDo not remove this section.\n");
        std::fs::write(&agents_md, &content).unwrap();

        std::fs::write(tmp.path().join("CLAUDE.md"), "v2 guidance").unwrap();
        execute_kb_export_guidance(&editor, &serde_json::json!({})).unwrap();

        let out = std::fs::read_to_string(&agents_md).unwrap();
        assert!(out.contains("Do not remove this section."));
        assert!(out.contains("v2 guidance"));
        assert!(!out.contains("v1 guidance"));
    }
}
